manifest = "287065576a4d67d38db229e820963574d146b1d1cda3c91a68fbec3a036165a5"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
target = "//:numeric_conversion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.34.1" ]
revision = "63d29f7b00c37e0a4181f5a0807e4a3437362d16"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.34.1" ]
revision = "cb908b531d1e80f28a57a8d053f12c9b6333d463"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.34.1" ]
revision = "78678e93a067c0cb555f7cef8471b85865298420"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.34.1" ]
revision = "a9fe7b7aee5ad5b824372ff9f0c2589687ed5879"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.34.1" ]
revision = "e9e481be77a29106a607e12bd315745fce67ac51"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.34.1" ]
revision = "96a068e01c182d6cf589293e9bac70a6ab914c23"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.34.1" ]
revision = "b600a1dcaa024efdf7520615d7d7dea1a653b327"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.34.1" ]
revision = "fa3d6dd897261bb1372ba88e9f9d3b825d364bc9"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.34.1" ]
revision = "c9e5103dbb8fb0ba31104a938c89484c126a0763"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.34.1" ]
revision = "6a3496f88d8a833351a52390cd20c0f6e64fe2b4"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.34.1" ]
revision = "12ac232daab5e01e1a57b1ca27f7625051602ba6"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.34.1" ]
revision = "e6e9e4c92f837811c99559042d8a901bff8feea5"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.34.1" ]
revision = "71f5486cb5e73631b113e3cc9348f78b46303be4"
