manifest = "45c125b23f5d0a15ab99a20ecb22e24c5e89254a65a4c9e8143eb2c749464015"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.19.0" ]
revision = "f08fd74e9cac1e7e76f11ff738bf7b768d1adb86"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.19.0" ]
revision = "3c49672be8a005624f03e630f8c30c3ca015d07a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.19.0" ]
revision = "8907705947c473ad9efe332af02d00b306df3541"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.19.0" ]
revision = "04669afca16be3373c217b2e0a2e20c7fa8aedb2"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.19.0" ]
revision = "ee411830944a8f928ad0627a9f115b4e90c21fb2"
