targets = [ "//:lexical-cast" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-container"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
version = "branch=master"
