manifest = "4a726c0312dd737662a506d17859918c957fb93dd1d620606e5bb96cfbb54138"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.25.1" ]
revision = "7beb73f77497223f1977616ec36df2a016b3c521"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.25.1" ]
revision = "506f73de6fa609a455f618dadb53af6e3ce3ac22"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.25.1" ]
revision = "778c84d4c767d9e75714fddfb34aec8907ee0fa0"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.25.1" ]
revision = "2c3123a6e0504ab0a303fd9cdc16837af2ef1f11"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.25.1" ]
revision = "f57224ef8f3ed8623c077e2ca32251c6f38e0471"
