targets = ["//:lexical_cast"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
version = "1.58.0"