manifest = "a854ee3d7b16ed867e54b13e8dac10ffd36d9b4fc69dfd4345e787cba94b37a2"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.31.0" ]
revision = "579dca1d04e09d63671bddde9aea5246af0eace5"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.31.0" ]
revision = "a83d1fbd2e2217c49e5ed2d4274bcdb812bcc0cd"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.31.0" ]
revision = "3c57233157a56605204d3818b73dc513e29b446a"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.31.0" ]
revision = "367fcb3e762a49fb82bca262e018f9653e6f1881"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.31.0" ]
revision = "0fe40a434ee2953887b8cc8f6f2aa442d287f503"
