manifest = "19b930a09d790d0cc1c67a529107792fa69020fa803da5ce88b86b607ce9a5da"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container"
target = "//:container"

[[dependency]]
package = "github.com/buckaroo-pm/boost-numeric_conversion"
target = "//:numeric_conversion"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.54.0" ]
revision = "77f4f05c57c3df5eb77475d10120bbf2cfd38b5e"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.54.0" ]
revision = "264be4423f4ec9a3d78ec0ab006fd113b7c5aa44"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.54.0" ]
revision = "110b58c9fdc5502003d1fbd5270cd6bcc8a1a09b"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "1.54.0" ]
revision = "523173c18f5b86df4500df056ba2a4e99a394d49"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.54.0" ]
revision = "d2f3338b08866620bbf261d40ff2cf53ffc956a3"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.54.0" ]
revision = "95cbdffbf6b327d13908e23e0f108ab28878a06c"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "1.54.0" ]
revision = "5886d845f899ac2b2a9f7ee48305dca5f0feb314"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.54.0" ]
revision = "e6677a308fc3f80fc6996d9ccd15b15e26892652"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.54.0" ]
revision = "0f5aa85faca5309527877994dd9d2054055b7f9f"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.54.0" ]
revision = "58a43792010b46145f3854ca3a9cf531c01c83f5"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.54.0" ]
revision = "07bc7ddde904bd61d3423b5b7342b7b0c4bd5602"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.54.0" ]
revision = "7c3a5c2a95ece09bf5f0ab53c4a7d50bf86ef46c"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.54.0" ]
revision = "fe33072bc96be57acebb59cbdd6178cf09d95ee8"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.54.0" ]
revision = "6252ee7fc574cd013c1ac1adb368b3948af184a7"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.54.0" ]
revision = "05bbb54685b47675ba8aa61232fada6dc08959f8"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.54.0" ]
revision = "c1329f3b7220b71a408de0db89c2f18dcae12bb7"
