manifest = "6df4f64a88660a85b4bd76ca9487e6e28909943cfcc47f54e8300b2e54b66fae"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.18.2" ]
revision = "5ee45f6df86db2ce2f70bc0e1b87625e4eb9abbe"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.18.2" ]
revision = "2bf83561dbe29c6a2f97e701b97009e21c960172"
