manifest = "35bd593fc3d2260ada0dc3169a35022278baa72c8b12df7459543a5308049123"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container"
target = "//:container"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "branch=master" ]
revision = "fb0dbf2f863db4b7dfc9e3cff17319e2d0a6a3df"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "d812ed3ac7c7d573249e49fe23aa12339629c730"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "branch=master" ]
revision = "545b0fbe13a3efea79f12e76cb837af147d4e4e8"
