manifest = "23ee259653e41f94a6e2dd83bb385b49a1c5e50da5bca434d099466e9d9cc639"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.20.1" ]
revision = "5874ea920f91801b48a794586c43b385cc3cb3f5"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.20.1" ]
revision = "b71cea233b5673794ba3e13c8aef6c1cf2c6c153"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.20.1" ]
revision = "4d677e43b65724abe40b56b7454d775ce8239c12"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.20.1" ]
revision = "339a0998312abb58509f10f35452b8e0c2ff691b"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.20.1" ]
revision = "050944b3039a2d45689eac176804c5e67c953c4a"
