manifest = "16d9c537ccb946eccd06c41cc413afbe0e844d97a8da33411a177c32ce61ec0f"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.23.0" ]
revision = "5f35fc5a4a7ae4e449f326b4bc84411402191de5"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.23.0" ]
revision = "70a7f134f7a2ca18b0a3dcdf62356ba7f0b33441"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.23.0" ]
revision = "6f32ccf3df54d8fb4a95f0be0cc838af677fac3d"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.23.0" ]
revision = "72127b50dde3e51fb64d0c6a61c94131cfd48ef4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.23.0" ]
revision = "d1b428093c830816aab337795fce8dc4d4fc9fa7"
