manifest = "df9d9e53ff27528afbec3338fcaa16b76bad41f11b08c965064b99a99fb2a45b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.21.0" ]
revision = "5621863a83acf3f6fa63fe328c5ee4a56e93ba52"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.21.0" ]
revision = "6e122e3ff3940ae29dc76e291f4ab2cff4381641"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.21.0" ]
revision = "0c2163004fb2806ed480bb374b5aa67c42968a5a"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.21.0" ]
revision = "ec5227804506b5bf86e478984828ceaa883e1d7e"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.21.0" ]
revision = "18c35e85ea26e344af3cc98dabb25499e24c1642"
