manifest = "3a2ac0bcc4371790e8cda4b9ce80740cde5607cbfa45b46504cc3bfb4e454b71"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.22.0" ]
revision = "2060cd12fe7c7a6467e1e0103395b6746b151985"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.22.0" ]
revision = "4a722040ab3870d65420eeb42494972513c9d35e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.22.0" ]
revision = "eb80c06574bddb04513ae64fccf563770e2b74db"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.22.0" ]
revision = "01d20d10f3d9894b3c4a7447adcb0c363e527413"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.22.0" ]
revision = "a546bba5f7af81f4b5533b6c78d9541618240a56"
