manifest = "791f7c26a32a670f150111e5d8ac3f72678b6d84c979b5be966ff10d01f8d07c"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container"
target = "//:container"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "branch=master" ]
revision = "a5b5d9d020d8e06e1cd311ee14e0cbc04557d6bf"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "5d18cdbcb05444b888687b0546112bef2e4d13c6"
