manifest = "79f4e78497879b973ff222884f280dc35199ec5b307e86911ecf87d3809a58cc"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.28.0" ]
revision = "bfe420eed80081e683f33949776cdd9d5603fe04"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.28.0" ]
revision = "e5f044291adec7ee599144608ac5856151558dae"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.28.0" ]
revision = "a5243efdf3ec2871379224c5e71cb3280548cfec"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.28.0" ]
revision = "46ef89e5690471340346c80e4105b71eed08b229"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.28.0" ]
revision = "b7bbe4aea8b0d9d79ee9a67d65070c9ac56d974c"
