manifest = "5ace937bb5e9d72710bf5daa00616ac92b1ce85a755ebcbc72691c482aa8d4b6"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
target = "//:array"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.18.3" ]
revision = "562abee5a2d75d41dcdf91ab57a747c93d63de9a"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.18.3" ]
revision = "1b1749271198bc9eaae81e349875abc0881f6b05"
